## Data wrangling

CBOE options data comes in a format that is different from the one we are currently using.  
We would like to have it all in a unified, tidy schema, with calls and puts separated into their own rows.

In [1]:
import pandas as pd

In [2]:
cboe = pd.read_csv("../data/scraped/cboe/SPX_20190310_to_20190312.csv")
historical = pd.read_csv("../data/allspx/SPX_2016.csv")

In [3]:
cboe.columns

Index(['Unnamed: 0', 'Expiration Date', 'Calls', 'Last Sale', 'Net', 'Bid',
       'Ask', 'Vol', 'IV', 'Delta', 'Gamma', 'Open Int', 'Strike', 'Puts',
       'Last Sale.1', 'Net.1', 'Bid.1', 'Ask.1', 'Vol.1', 'IV.1', 'Delta.1',
       'Gamma.1', 'Open Int.1'],
      dtype='object')

In [4]:
historical.columns

Index(['underlying', 'underlying_last', ' exchange', 'optionroot', 'optionext',
       'type', 'expiration', 'quotedate', 'strike', 'last', 'bid', 'ask',
       'volume', 'openinterest', 'impliedvol', 'delta', 'gamma', 'theta',
       'vega', 'optionalias'],
      dtype='object')

In [5]:
cboe.head()

,Unnamed: 0,Expiration Date,Calls,Last Sale,Net,Bid,Ask,Vol,IV,Delta,...,Puts,Last Sale.1,Net.1,Bid.1,Ask.1,Vol.1,IV.1,Delta.1,Gamma.1,Open Int.1
0,0,03/13/2019,SPXW190313C01700000,0.0,0.00,1086.2,1097.5,0,0.0000,0.9975,...,SPXW190313P01700000,0.05,0.025,0.0,0.05,3,2.5010,-0.0002,0.0,79
1,1,03/13/2019,SPXW190313C01800000,0.0,0.00,986.9,998.3,0,2.9426,0.9961,...,SPXW190313P01800000,0.00,0.000,0.0,0.05,0,2.2504,-0.0003,0.0,34
2,2,03/13/2019,SPXW190313C01850000,0.0,0.00,935.9,947.3,0,0.0000,0.9988,...,SPXW190313P01850000,0.00,0.000,0.0,0.05,0,2.0922,-0.0003,0.0,19
3,3,03/13/2019,SPXW190313C01900000,890.0,7.55,886.1,897.3,2,0.0000,0.9980,...,SPXW190313P01900000,0.00,0.000,0.0,0.05,0,1.9698,-0.0003,0.0,15
4,4,03/13/2019,SPXW190313C01950000,0.0,0.00,836.2,847.6,0,0.0000,0.9968,...,SPXW190313P01950000,0.00,0.000,0.0,0.05,0,1.8414,-0.0003,0.0,16

In [6]:
historical.head()

,underlying,underlying_last,exchange,optionroot,optionext,type,expiration,quotedate,strike,last,bid,ask,volume,openinterest,impliedvol,delta,gamma,theta,vega,optionalias
0,SPX,2008.87,*,SPX160115C00300000,NaN,call,01/15/2016,01/04/2016,300,1748.7,1712.6,1716.5,0,23,0.157,1.0,0.0,-1.8585,0.0,SPX160115C00300000
1,SPX,2008.87,*,SPX160115C00400000,NaN,call,01/15/2016,01/04/2016,400,0.0,1612.7,1616.5,0,0,0.157,1.0,0.0,-2.4780,0.0,SPX160115C00400000
2,SPX,2008.87,*,SPX160115C00500000,NaN,call,01/15/2016,01/04/2016,500,1551.7,1512.7,1516.7,0,2281,0.157,1.0,0.0,-3.0975,0.0,SPX160115C00500000
3,SPX,2008.87,*,SPX160115C00600000,NaN,call,01/15/2016,01/04/2016,600,1425.5,1412.5,1416.7,0,15,0.157,1.0,0.0,-3.7169,0.0,SPX160115C00600000
4,SPX,2008.87,*,SPX160115C00700000,NaN,call,01/15/2016,01/04/2016,700,1249.4,1312.7,1316.8,0,14,0.157,1.0,0.0,-4.3364,0.0,SPX160115C00700000

In [17]:
call_columns = ["Calls", "Expiration Date", "Strike", "Last Sale", "Net", "Bid", "Ask", "Vol", "Open Int", "IV", "Delta", "Gamma"]

In [29]:
calls = cboe[call_columns]
calls.rename(columns={"Calls": "optionroot"})
calls.head()

,Calls,Expiration Date,Strike,Last Sale,Net,Bid,Ask,Vol,Open Int,IV,Delta,Gamma
0,SPXW190313C01700000,03/13/2019,1700.0,0.0,0.00,1086.2,1097.5,0,1,0.0000,0.9975,0.0
1,SPXW190313C01800000,03/13/2019,1800.0,0.0,0.00,986.9,998.3,0,0,2.9426,0.9961,0.0
2,SPXW190313C01850000,03/13/2019,1850.0,0.0,0.00,935.9,947.3,0,0,0.0000,0.9988,0.0
3,SPXW190313C01900000,03/13/2019,1900.0,890.0,7.55,886.1,897.3,2,24,0.0000,0.9980,0.0
4,SPXW190313C01950000,03/13/2019,1950.0,0.0,0.00,836.2,847.6,0,0,0.0000,0.9968,0.0

In [20]:
put_columns = ["Puts", "Expiration Date", "Strike", "Last Sale.1", "Net.1", "Bid.1", "Ask.1", "Vol.1", "Open Int.1", "IV.1", "Delta.1", "Gamma.1"]

In [21]:
puts = cboe[put_columns]
puts.columns
puts.head()

,Puts,Expiration Date,Strike,Last Sale.1,Net.1,Bid.1,Ask.1,Vol.1,Open Int.1,IV.1,Delta.1,Gamma.1
0,SPXW190313P01700000,03/13/2019,1700.0,0.05,0.025,0.0,0.05,3,79,2.5010,-0.0002,0.0
1,SPXW190313P01800000,03/13/2019,1800.0,0.00,0.000,0.0,0.05,0,34,2.2504,-0.0003,0.0
2,SPXW190313P01850000,03/13/2019,1850.0,0.00,0.000,0.0,0.05,0,19,2.0922,-0.0003,0.0
3,SPXW190313P01900000,03/13/2019,1900.0,0.00,0.000,0.0,0.05,0,15,1.9698,-0.0003,0.0
4,SPXW190313P01950000,03/13/2019,1950.0,0.00,0.000,0.0,0.05,0,16,1.8414,-0.0003,0.0